import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ArrowLeft, MoreHorizontal, Pencil, Trash2, FolderInput, CalendarDays, Library, Loader2 } from 'lucide-react'
import { listOutputs, updateLecture, watchLecture, watchSources } from '../lib/db'
import { deleteLecture } from '../lib/pipeline'
import { generate, runKey, useRunning } from '../lib/genStore'
import { exportAnki, exportCsv } from '../lib/export'
import { slug } from '../lib/format'
import type { Flashcard, GlossaryTerm, Lecture, MarkdownContent, Output, OutputType, PodcastContent, QuizQuestion, Source, SummaryContent, Visual } from '../lib/types'
import { useCourses, COURSE_COLORS } from '../hooks/useCourses'
import SourcesPanel, { AddSourceModal } from '../components/SourcesPanel'
import ToolPanel from '../components/tools/ToolPanel'
import { OUTPUT_META, TAB_ORDER, CHAT_META } from '../components/tools/meta'
import SummaryView from '../components/tools/SummaryView'
import FlashcardsView from '../components/tools/FlashcardsView'
import QuizView from '../components/tools/QuizView'
import PodcastView from '../components/tools/PodcastView'
import VisualsView from '../components/tools/VisualsView'
import GlossaryView from '../components/tools/GlossaryView'
import ChatView from '../components/tools/ChatView'
import Markdown from '../components/Markdown'
import CourseSelect from '../components/CourseSelect'
import { Button, IconButton, Menu, MenuItem, Modal, PageSpinner, cx, useToast } from '../components/ui'
import { FileSpreadsheet, Layers } from 'lucide-react'
import { ApiError } from '../lib/api'

